Repository Ceredira/CerediraTess_Test, pull requests merged in 2022-05, with the labels that each got.

#17 fix users
  1. Компоненты/0. Шаги/1. Войти на сайт с пользователем username.md
  1. Компоненты/0. Шаги/2. Создать скрипт с именем test_name.md
  1. Компоненты/0. Шаги/3. Создать пользователя username.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/2. Создание пользователя.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Просмотр записи пользователя.md
Labels: test_case

#18 fix steps
  1. Компоненты/0. Шаги/1. Войти на сайт с пользователем username.md
  1. Компоненты/0. Шаги/2. Создать скрипт с именем test_name.md
  1. Компоненты/0. Шаги/3. Создать пользователя username.md
  1. Компоненты/0. Шаги/4. Создать роль с именем userrole.md
Labels: test_case

#21 add path
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/4. Изменение записи пользователя, изменение поля Логин пользователя.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Просмотр записи пользователя.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/10. Дублирование записи роли, негативный сценарий.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/11. Удаление записи роли admin, негативный сценарий.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/12. Удаление записи роли через выбор.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/13. Удаление записей ролей через выбор Все, негативный сценарий.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/5. Изменение роли, изменение поля Описание.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/6. Просмотр роли.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/7. Дублирование записи роли, позитивный сценарий (1 способ).md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/8. Дублирование записи роли, позитивный сценарий (2 способ).md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/9. Дублирование записи роли, позитивный сценарий (3 способ).md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/1. Создание скрипта (новой записи).md
Labels: test_case

#23 fix scripts
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/1. Создание скрипта (новой записи).md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/10. Удаление записи скрипта через выбор.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/11. Удаление записи скрипта через выбор Все.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/12. Сортировка в столбце Имя скрипта.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/13. Дублирование скрипта. Сохранить и продолжить редактирование без внесения изменений.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/14. Дублирование скрипта. Сохранить и продолжить редактирование ввести имя уже существующего скрипта.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/15. С выбранным. Удалить без выбора.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/15. Удаление записей скриптов через выбор. Удалить без выбора.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/16. Дублирование скрипта. Отмена (вез введения данных).md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/17. Сортировка в столбце Описание.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/2. Удаление записи скрипта, когда остался 1 скрипт.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/3. Удаление записи скрипта, когда скрипт не последний.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/4. Изменение записи скрипта, изменение поля Описание.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/5. Изменение записи скрипта, изменение поля Имя скрипта.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/6. Просмотр записи скрипта.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/7. Дублирование записи скрипта, позитивный сценарий (1 способ).md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/8. Дублирование записи скрипта, позитивный сценарий (2 способ).md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/9. Дублирование записи скрипта, негативный сценарий.md
Labels: test_case

#24 Добавила Подтверждение пароля
  1. Компоненты/0. Шаги/3. Создать пользователя username.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/2. Создание пользователя.md
Labels: test_case

#25 Delete unused data
  0. Подготовка окружения тестирования/Ntcnjdsq.txt
  0. Подготовка окружения тестирования/Testdoc.txt
  autotests/.gitignore
  autotests/test/test_login.py
Labels: enhancement

#26 Renumbering files
  0. Подготовка окружения тестирования/1. Скачивание образа Windows 10.md
  0. Подготовка окружения тестирования/2. Установка VMware.md
  0. Подготовка окружения тестирования/3. Запуск и настройка VMware.md
  0. Подготовка окружения тестирования/4. Установка Windows в виртуальную машину.md
  0. Подготовка окружения тестирования/5. Создание рабочего каталога.md
  0. Подготовка окружения тестирования/6.1. Установка HDDScanner.md
  0. Подготовка окружения тестирования/6.2. Установка Everything.md
  0. Подготовка окружения тестирования/6.3. Установка Notepad++.md
  0. Подготовка окружения тестирования/6.4. Установка SublimeText4.md
  0. Подготовка окружения тестирования/6.5. Установка WinMerge.md
  0. Подготовка окружения тестирования/6.6. Установка и настройка Git.md
  0. Подготовка окружения тестирования/7. Создание ярлыков инструментов.md
Labels: enhancement

#28 Исправление нумерации в вызываемых шагах
  1. Компоненты/0. Шаги/5. Создать агент agent с типом ОС os_type.md
  1. Компоненты/0. Шаги/6. Создать агент agent, заблокированный lock_user, с причиной lock_cause, с типом ОС os_type, со скриптами scripts, добавленный к ролям roles, с описанием description.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/1. Редактирование агента в поле ввода Адрес агента (FQDN).md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/10. Удаление агента, когда записей в списке 1.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/11. Удаление агента, когда запись не последняя.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/2. Просмотр записи агента со всеми заполненными столбцами.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/3. Редактирование агента в поле ввода Кем заблокировано.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/4. Редактирование агента в поле ввода Описание.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/5. Редактирование агента в поле ввода Причина блокировки.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/6. Редактирование агента в поле ввода Роли.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/7. Редактирование агента в поле ввода Тип ОС.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/8. Создание агента. Заполнение всех полей.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/9. Удаление агента через выбор все .md
Labels: test_case

#27 Добавлены требования
  Требования/CerediraTess.puml
  Требования/CerediraTess.puml.svg
Labels: enhancement

#31 add positive tests
  1. Компоненты/0. Шаги/10. Создать агент agent с типом ОС os_type и с ролью role.md
  1. Компоненты/0. Шаги/8. Заблокировать агент agent с причиной lock_cause.md
  1. Компоненты/0. Шаги/9. Разблокировать агент agent с причиной lock_cause.md
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/1.  Блокировка 1 агента.md
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/3.  Блокировка n агентов.md
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/4.  Разблокировка n агентов.md
Labels: test_case

#35 fix bug 33
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/10. Дублирование записи роли, негативный сценарий.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/11. Удаление записи роли admin, негативный сценарий.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Роли/13. Удаление записей ролей через выбор Все, негативный сценарий.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/13. Дублирование скрипта. Сохранить и продолжить редактирование без внесения изменений.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/9. Дублирование записи скрипта, негативный сценарий.md
Labels: bug, test_case

#34 add tests
  1. Компоненты/0. Шаги/7.  Добавление скриптов scripts для существующего агента agent.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/12. Проверка существования, при старте с нуля, агента CerediraTess.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Выполнение запросов/1. Обновление скриптов.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Выполнение запросов/2. Добавление скрипта, когда файл скрипта удален.md
Labels: test_case

#37 update checkbox name
  1. Компоненты/0. Шаги/3. Создать пользователя username.md
  1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/2. Создание пользователя.md
Labels: bug, test_case

#38 Update preconditions
  1. Компоненты/1. Веб-интерфейс/0. Предусловия/preconditions.md
Labels: documentation

#39 Add negative cases
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/10. Разблокировка n заблокированных агентов с другой причиной.md
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/5. Блокировка 1 заблокированного агента c такой же причиной.md
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/6. Блокировка n заблокированных агентов c такой же причиной.md
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/7. Блокировка 1 заблокированного агента c другой причиной.md
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/8. Блокировка n заблокированных агентов c другой причиной.md
  1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/9. Разблокировка 1 заблокированного агента с той же причиной.md
Labels: test_case
